---
title: "EDA"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

```{r}

df <- read_csv("data/OnlineNewsPopularity.csv")

df %>%
  ggplot(aes(n_tokens_title)) +
  geom_histogram(binwidth=1)



df %>%
  filter(n_non_stop_words < 5) %>%
  ggplot(aes(n_unique_tokens)) +
  geom_histogram(binwidth=0.01)


normal_df %>%
  ggplot(aes(n_tokens_content)) +
  geom_histogram(binwidth=1)




df %>%
  filter(n_non_stop_words < 5) %>%
  ggplot(aes(n_non_stop_unique_tokens)) +
  geom_histogram(binwidth=0.01)

df %>%
  ggplot(aes(num_hrefs)) +
  geom_histogram(binwidth=1)

df %>%
  ggplot(aes(num_self_hrefs)) +
  geom_histogram(binwidth=1)

non_zero_df %>%
  ggplot(aes(average_token_length)) +
  geom_histogram(binwidth=0.01)

df %>%
  pivot_longer(data_channel_is_lifestyle:data_channel_is_world, names_to = "channel", values_to = "isnot") %>% 
  filter(isnot ==1) %>%
  ggplot(aes(x = channel)) +
  geom_bar() +
  coord_flip()
  



```

```{r}
zero_df <- df %>%
  filter(n_tokens_content == 0)

non_zero_df <- df %>%
  filter(n_tokens_content > 0)

long_df <- df %>%
  filter(n_tokens_content > 700)



normal_df <- df %>%
  filter(n_tokens_content < 700 & n_tokens_content > 0)
  

```

```{r}
#rapid check of the dataset
View(df)
summary(df)
str(df)
sum(is.na(df))

#first 250 rows of the data set
datatable(
  df[1:250,],
  rownames = FALSE,
  filter = "top",
  options = list(pageLength = 5, scrollX = T)
)#we need to be in Rmd to run this code (later, when we need to knit)

#global EDA for all features
view(dfSummary(df, style = "grid",plain.ascii = FALSE, tmp.img.dir = "/tmp"))

#creating shares popularity classes
share_label <- cut(df$shares, breaks = c(0, 645, 861, 1400, 31300, 53700, 77200, 843300))
levels(share_label) <- c("Very Poor", "Poor", "Average", "Good", "Very Good", "Excellent", "Exceptional")

new <- data_frame(df, share_label, )
#global shares
options(scipen = 999)
df %>% ggplot(aes(x = shares)) +
  geom_boxplot(color = "black", fill = "grey") + xlab("")
df %>% ggplot(aes(x = shares)) +
  geom_histogram(color = "black", fill = "grey")

#log_transformation
df$shares <- log(df$shares)
hist(
  df$shares,
  freq = FALSE,
  col = "grey",
  main = "Distribution of Log transformed Shares",
  xlab = "Log_shares"
) #histogram

curve(
  dnorm(
    x,
    mean = mean(df$shares),
    sd = sd(df$shares)
  ),
  col = 2,
  lty = 1,
  lwd = 2,
  add = TRUE
) #theoretical curve

#by label
new %>%
  group_by(share_label) %>%
  summarise(n = n()) %>% ungroup() %>% 
  mutate(share_label = reorder(share_label, n)) %>%
  ggplot(aes(x = share_label, y = n)) +
  geom_col() +
  geom_segment(aes(
    x = share_label ,
    xend = share_label,
    y = 0,
    yend = n
  ), color = "grey") +
  geom_point(size = 3, color = "#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  xlab("")

a <- new %>% group_by(share_label) %>% summarise(n = n()) %>% ungroup()
View(a)
b <- new %>% group_by(share_label) %>% summarise(n = n()) %>% summarise(prop = n/sum(n))  %>% ungroup()
pc_shares <- data_frame(a,b)


#Sentiment analysis is basically the process of determining the attitude or the emotion of the writer, i.e., whether it is positive or negative or neutral.
#The sentiment function of textblob returns two properties, polarity, and subjectivity.
#Polarity is float which lies in the range of [-1,1] where 1 means positive statement and -1 means a negative statement.
#Subjective sentences generally refer to personal opinion, emotion or judgment whereas objective refers to factual information.
#Subjectivity is also a float which lies in the range of [0,1].

#positive/negative among non-neutral token
df %>% ggplot(aes(x = rate_positive_words)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = rate_positive_words)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

df %>% ggplot(aes(x = rate_negative_words)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = rate_negative_words)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

df %>% ggplot(aes(x = avg_positive_polarity)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = avg_positive_polarity)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

df %>% ggplot(aes(x = avg_negative_polarity)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = avg_negative_polarity)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

#positive/negative subjectivity title token
df %>% ggplot(aes(x = title_subjectivity)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = title_subjectivity)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

df %>% ggplot(aes(x = title_sentiment_polarity)) +
  geom_boxplot(color = "black", fill = "grey")#BOXPLOT
df %>% ggplot(aes(x = title_sentiment_polarity)) +
  geom_histogram(color = "black", fill = "grey")#HISTOGRAM

#polarity and subjectivity given shares popularity classes
new %>% group_by(share_label) %>% summarise(mean(title_sentiment_polarity))
new %>% group_by(share_label) %>% summarise(mean(title_sentiment_polarity)) %>%
  ggplot(aes(x = share_label, y = `mean(title_sentiment_polarity)`)) + geom_bar(stat = "identity") + ggtitle("Title Sentimental Polarity given Shares Popularity") + xlab("Popularity Label") + ylab("Mean Sentiment Polarity") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 

new %>% group_by(share_label) %>% summarise(mean(title_subjectivity)) %>%
  ggplot(aes(x = share_label, y = `mean(title_subjectivity)`)) + geom_bar(stat = "identity")+ ggtitle("Title Sentimental Subjectivity given Shares Popularity") + xlab("Popularity Label") + ylab("Mean Subjectivity") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```
