Machine learning project : Mashable Online news popularity

Section 1: Introduction

In the context of business analytics, one of the most common uses of data science by companies today is online product promotion. Whether the goal is promoting a physical product through digital marketing and social media, or whether the product to be promoted is a piece of media (article, video etc.) which generates revenue through advertisements, engagement is the name of the game. Engagement can be measured though shares, likes, comments depending on the platform where these interactions happen. We have found a dataset, that allows us to explore the possibilities of predicting the popularity of online content based on information about the content itself.  In our case, we have data on the number of shares for articles posted on the Mashable website, and this is the variable that we will be trying to predict in this project. The rest of the dataset contains values from text mining techniques that have already been performed on the articles, as well as data on the presence of images or videos in the articles. We will use these variables to try to predict the popularity of the articles, measured in shares. 
In the next section, we will proceed to describe the data, which will be followed by Section 3, where will discuss the results of our exploratory data analysis, Section 4, where we will discuss our methods for the prediction model and Section 5, where will discuss the results of our analysis and the conclusions that we can take from them.

## Text to be added to conclusion

References

[1] K. Fernandes, P. Vinagre and P. Cortez. A Proactive Intelligent Decision Support System for Predicting the Popularity of Online News. Proceedings of the 17th EPIA 2015 - Portuguese Conference on Artificial Intelligence, September, Coimbra, Portugal.

[2] H. Ren, Q. Yang. Predicting and Evaluating the Popularity of Online News. Stanford University Press 2015
