# Conclusion

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

<br>

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

The aim of this project was to apply several algorithms on a dataset in order to explore the possibilities of predicting the popularity of online content based on information about the content itself. The algorithm with the best predictive power is a random forest with an mtry = 2.5, which gives us a prediction accuracy of about 65%. On the same algorithm, the literature tends to have a slightly higher score. However, they tended to use all the features, which somewhat increases the chance of overfitting in their models. We have chosen the features that can be generalised to other texts, and that seem to be easier to interpret for someone without deep knowledge of NLP. To the extent that we achieve results not too far from what we have seen in the literature, we think we have effectively reduced the dataset to the most understandable features without lsoing too much in terms of accuracy.

We also wanted to test the predictive power of our best algorithm on articles with particularly high popularity. This has not been done before in the literature. The aim was to predict the types of content that could generate very high engagement and therefore could reach a very large number of people. 

However, we believe that the results in our study and in the literature are not strong enough for us to be able to recommend to companies to use this combination of NLP and machine learning techniques.There is also some question about the quality of the data, as we have found in a manual verification of some instances the dataset that some of the word counts in the specific articles are incorrect, making the values of the other features also somewhat questionable. 

Overall, it is probable that the features related to NLP, even if collected without any errors, would not be able to provide a very high accuracy. There is perhaps an intangible and random dimension to internet buzz that data such as this are not able to capture. We think that future studies that attempt to replicate such techniques should be wary both of this fact and also of the possibility of errors when automated NLP techniques interact with the webpage format.


</div>


## References

[1] K. Fernandes, P. Vinagre and P. Cortez. A Proactive Intelligent Decision Support System for Predicting the Popularity of Online News. Proceedings of the 17th EPIA 2015 - Portuguese Conference on Artificial Intelligence, September, Coimbra, Portugal.

[2] H. Ren, Q. Yang. Predicting and Evaluating the Popularity of Online News. Stanford University Press 2015