
```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

```{r}
normal_df %>%
  pivot_longer(
    data_channel_is_lifestyle:data_channel_is_world,
    names_to = "channel",
    values_to = "isnot"
  ) %>%
  filter(isnot == 1) %>%
  ggplot(aes(x = channel)) +
  geom_bar() +
  coord_flip()
```

```{r}
#log_transformation
df$shares <- log(df$shares)
hist(
  df$shares,
  freq = FALSE,
  col = "grey",
  main = "Distribution of Log transformed Shares",
  xlab = "Log_shares"
) #histogram
```

```{r}
#by label
final_df %>%
  group_by(share_label) %>%
  summarise(n = n()) %>% ungroup() %>% 
  mutate(share_label = reorder(share_label, n)) %>%
  ggplot(aes(x = share_label, y = n)) +
  geom_col() +
  geom_segment(aes(
    x = share_label ,
    xend = share_label,
    y = 0,
    yend = n
  ), color = "grey") +
  geom_point(size = 3, color = "#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  xlab("")
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(n_tokens_title)) %>%
  ggplot(aes(x = share_label, y = `mean(n_tokens_title)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Number of Token in the title") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(n_tokens_content)) %>%
  ggplot(aes(x = share_label, y = `mean(n_tokens_content)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Number of Token in the article") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(n_unique_tokens)) %>%
  ggplot(aes(x = share_label, y = `mean(n_unique_tokens)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("?") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(num_hrefs)) %>%
  ggplot(aes(x = share_label, y = `mean(num_hrefs)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Ref") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(num_imgs)) %>%
  ggplot(aes(x = share_label, y = `mean(num_imgs)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Number of Images") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(num_videos)) %>%
  ggplot(aes(x = share_label, y = `mean(num_videos)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Number of Videos") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(num_keywords)) %>%
  ggplot(aes(x = share_label, y = `mean(num_keywords)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Keyword") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(num_keywords)) %>%
  ggplot(aes(x = share_label, y = `mean(num_keywords)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Keyword") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(self_reference_avg_sharess)) %>%
  ggplot(aes(x = share_label, y = `mean(self_reference_avg_sharess)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Keyword") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(self_reference_avg_sharess)) %>%
  ggplot(aes(x = share_label, y = `mean(self_reference_avg_sharess)`)) +
  geom_bar(stat = "identity") +
  ggtitle("") +
  xlab("Popularity Label") +
  ylab("Mean Keyword") +
  theme(plot.title = element_text(hjust = 0.5)) #BARPLOT 
```

```{r}
#Sentiment analysis is basically the process of determining the attitude or the emotion of the writer, i.e., whether it is positive or negative or neutral.
#The sentiment function of textblob returns two properties, polarity, and subjectivity.
#Polarity is float which lies in the range of [-1,1] where 1 means positive statement and -1 means a negative statement.
#Subjective sentences generally refer to personal opinion, emotion or judgment whereas objective refers to factual information.
#Subjectivity is also a float which lies in the range of [0,1].

#polarity and subjectivity given shares popularity classes

final_df %>% group_by(share_label) %>% summarise(mean(title_sentiment_polarity)) %>%
  ggplot(aes(x = share_label, y = `mean(title_sentiment_polarity)`)) +
  geom_bar(stat = "identity") + ggtitle("Title Sentimental Polarity given Shares Popularity") +
  xlab("Popularity Label") +
  ylab("Mean Sentiment Polarity") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
final_df %>%
  group_by(share_label) %>%
  summarise(mean(title_subjectivity)) %>%
  ggplot(aes(x = share_label, y = `mean(title_subjectivity)`)) +
  geom_bar(stat = "identity") +
  ggtitle("Title Sentimental Subjectivity given Shares Popularity") +
  xlab("Popularity Label") +
  ylab("Mean Subjectivity") +
  theme(plot.title = element_text(hjust = 0.5))#BARPLOT 
```

```{r}
ggplot(data = new, aes(data_channel, log(shares))) + geom_boxplot()
```

```{r}
ggplot(data = new, aes(day, log(shares))) + geom_boxplot()
```

```{r}
ggplot(data = new, aes(day_is_weekend, log(shares))) + geom_boxplot()
```
